"""Added relationships

Revision ID: 40b717069152
Revises: d3d4d63da323
Create Date: 2023-07-19 10:32:17.045105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40b717069152'
down_revision = 'd3d4d63da323'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
