"""added relationship inbetween the classes

Revision ID: 83742acca13b
Revises: f4dfe522987d
Create Date: 2023-07-19 10:00:36.584264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83742acca13b'
down_revision = 'f4dfe522987d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('puzzle_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['puzzle_id'], ['puzzles.id'], name=op.f('fk_outcomes_puzzle_id_puzzles')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('situations')
    with op.batch_alter_table('choices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('outcome_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_choices_outcome_id_outcomes'), 'outcomes', ['outcome_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('choices', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_choices_outcome_id_outcomes'), type_='foreignkey')
        batch_op.drop_column('outcome_id')

    op.create_table('situations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('outcomes')
    # ### end Alembic commands ###
