"""added question to Puzzle class

Revision ID: aa62ba9351be
Revises: 3b66a4d6447e
Create Date: 2023-07-19 08:26:51.709609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa62ba9351be'
down_revision = '3b66a4d6447e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('situations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('choices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('puzzle_id', sa.Integer(), nullable=True),
    sa.Column('answer', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['puzzle_id'], ['puzzles.id'], name=op.f('fk_choices_puzzle_id_puzzles')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('puzzles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('puzzles', schema=None) as batch_op:
        batch_op.drop_column('question')

    op.drop_table('choices')
    op.drop_table('situations')
    # ### end Alembic commands ###
