"""added relationship inbetween the classes

Revision ID: d3d4d63da323
Revises: 83742acca13b
Create Date: 2023-07-19 10:18:48.037908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3d4d63da323'
down_revision = '83742acca13b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
