"""added if __name__

Revision ID: f4dfe522987d
Revises: aa62ba9351be
Create Date: 2023-07-19 09:21:21.937185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4dfe522987d'
down_revision = 'aa62ba9351be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
