"""filled out the classes tables

Revision ID: f4fa028ab004
Revises: 40b717069152
Create Date: 2023-07-19 14:17:51.466453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4fa028ab004'
down_revision = '40b717069152'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
